### ISSUE TITLE
这个agronne改颜色了？？

### ISSUE THREAD

**Issue by bravodilove** [kenzok78/luci-theme-argone#1]
这个agronne改颜色了？？ 这颜色没法看啊

**Comment by doumeki** [comment]
确实，太难看了。argon主题设置也用不了。
登录界面的壁纸都没了

**Comment by lgs2007m** [comment]
> 确实，太难看了。argon主题设置也用不了。 登录界面的壁纸都没了

壁纸问题应该是Makefile的问题，看我提的issues https://github.com/kenzok78/luci-theme-argonne/issues/3

**Comment by lgs2007m** [comment]
> 这个agronne改颜色了？？ 这颜色没法看啊

主题的亮暗模式的颜色，你修改为输入框下面提示的默认值试试。
大佬在另外一边回复了，可以看看https://github.com/kenzok8/small-package/issues/22#issuecomment-1057611411
