### ISSUE TITLE
luci-theme-argonne主题的Makefile文件好像有错误，导致编译后登录界面不能显示背景图

### ISSUE THREAD

**Issue by lgs2007m** [kenzok78/luci-theme-argone#3]
luci-theme-argonne的Makefile中有一行：
`[ -f /usr/lib/lua/luci/view/themes/argon/out_header_login.htm ] && mv -f /usr/lib/lua/luci/view/themes/argon/out_header_login.htm /usr/lib/lua/luci/view/header_login.htm`
其中的argon未修改为argonne，导致编译后登录界面不能显示背景图。通过手动修改移动路由器的/usr/lib/lua/luci/view/themes/argon/out_header_login.htm到/usr/lib/lua/luci/view/header_login.htm后就正常了。

@kenzok8  请大佬检查修改下。

登录界面不能显示背景图：
![bg1](https://user-images.githubusercontent.com/22903593/156487503-d0406895-8f8d-4e54-8fb8-48bcd6d057de.jpg)

**Comment by lgs2007m** [comment]
已看到修改了，谢谢大佬。

**Comment by anjue39** [comment]
The requested URL /luci-static/argonne/img/argonne.svg was not found on this server.
这个图标不显示

**Comment by lgs2007m** [comment]
> The requested URL /luci-static/argonne/img/argonne.svg was not found on this server. 这个图标不显示

源码库[img](https://github.com/kenzok78/luci-theme-argonne/tree/main/htdocs/luci-static/argonne/img)中的文件已经修改为argonne.svg了，你再编译试试。

不重新编译也可以先切换到其他主题，然后修改路由器中/rom/www/luci-static/argonne/img/argon.svg这个文件名为argonne.svg，再启用argonne主题就行了

**Comment by anjue39** [comment]
好的👌



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lgs2007m ***@***.***&gt;
发送时间: 2022年3月6日 13:59
收件人: kenzok78/luci-theme-argonne ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [kenzok78/luci-theme-argonne] luci-theme-argonne主题的Makefile文件好像有错误，导致编译后登录界面不能显示背景图 (Issue #3)

**Comment by anjue39** [comment]
是图片url所在服务器的问题我觉得，一开始进入源码库，直接打开也加载不了，后根据网上提示，host加入服务器的ip才能加载



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lgs2007m ***@***.***&gt;
发送时间: 2022年3月6日 13:59
收件人: kenzok78/luci-theme-argonne ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [kenzok78/luci-theme-argonne] luci-theme-argonne主题的Makefile文件好像有错误，导致编译后登录界面不能显示背景图 (Issue #3)

**Comment by lgs2007m** [comment]
> 是图片url所在服务器的问题我觉得，一开始进入源码库，直接打开也加载不了，后根据网上提示，host加入服务器的ip才能加载 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: lgs2007m ***@***.***&gt; 发送时间: 2022年3月6日 13:59 收件人: kenzok78/luci-theme-argonne ***@***.***&gt; 抄送: anjue39 ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [kenzok78/luci-theme-argonne] luci-theme-argonne主题的Makefile文件好像有错误，导致编译后登录界面不能显示背景图 (Issue #3)

这样子嘛，我是在线编译的不清楚什么情况。你能解决就好。

**Comment by anjue39** [comment]
我也是在线编译的，按说不存在这种情况。你那边最近编译的没这个问题？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lgs2007m ***@***.***&gt;
发送时间: 2022年3月6日 17:01
收件人: kenzok78/luci-theme-argonne ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [kenzok78/luci-theme-argonne] luci-theme-argonne主题的Makefile文件好像有错误，导致编译后登录界面不能显示背景图 (Issue #3)





  
是图片url所在服务器的问题我觉得，一开始进入源码库，直接打开也加载不了，后根据网上提示，host加入服务器的ip才能加载 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: lgs2007m @.&gt; 发送时间: 2022年3月6日 13:59 收件人: kenzok78/luci-theme-argonne @.&gt; 抄送: anjue39 @.&gt;, Comment @.&gt; 主题: Re: [kenzok78/luci-theme-argonne] luci-theme-argonne主题的Makefile文件好像有错误，导致编译后登录界面不能显示背景图 (Issue #3)
  
这样子嘛，我是在线编译的不清楚什么情况。你能解决就好。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lgs2007m** [comment]
> 我也是在线编译的，按说不存在这种情况。你那边最近编译的没这个问题？ 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: lgs2007m ***@***.***&gt; 发送时间: 2022年3月6日 17:01 收件人: kenzok78/luci-theme-argonne ***@***.***&gt; 抄送: anjue39 ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [kenzok78/luci-theme-argonne] luci-theme-argonne主题的Makefile文件好像有错误，导致编译后登录界面不能显示背景图 (Issue #3) 是图片url所在服务器的问题我觉得，一开始进入源码库，直接打开也加载不了，后根据网上提示，host加入服务器的ip才能加载 发自我的iPhone … ------------------ 原始邮件 ------------------ 发件人: lgs2007m @.&gt; 发送时间: 2022年3月6日 13:59 收件人: kenzok78/luci-theme-argonne @.&gt; 抄送: anjue39 @.&gt;, Comment @.&gt; 主题: Re: [kenzok78/luci-theme-argonne] luci-theme-argonne主题的Makefile文件好像有错误，导致编译后登录界面不能显示背景图 (Issue #3) 这样子嘛，我是在线编译的不清楚什么情况。你能解决就好。 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***&gt;

我浏览器有缓存，之前没发现这个问题。看到你说，我用另外浏览器打开，才发现了登录界面用户名上面图标不显示。我昨天编译的，看了也有这个问题。我手动改路由器里面文件的名字就好了
