### ISSUE TITLE
新版本显示有问题

### ISSUE THREAD

**Issue by mzl0408** [kenzok78/luci-theme-argone#4]
最新的版本编译的，出来后主题显示有问题，好多图标都是框框

**Comment by davidtall** [comment]
同样的问题，icon 显示不出来，目测是字体文件报错了。F12 控制台显示报错
Failed to decode downloaded font: http://192.168.0.1/luci-static/argonne/fonts/argonne.ttf?u6kthm
Failed to decode downloaded font: http://192.168.0.1/luci-static/argonne/fonts/argonne.woff?u6kthm
![image](https://user-images.githubusercontent.com/9320941/164739501-f4b4a332-cc27-41ff-9d1e-f4715458ff9b.png)

**Comment by mzl0408** [comment]
> 同样的问题，icon 显示不出来，目测是字体文件报错了。F12 控制台显示报错 Failed to decode downloaded font: http://192.168.0.1/luci-static/argonne/fonts/argonne.ttf?u6kthm Failed to decode downloaded font: http://192.168.0.1/luci-static/argonne/fonts/argonne.woff?u6kthm ![image](https://user-images.githubusercontent.com/9320941/164739501-f4b4a332-cc27-41ff-9d1e-f4715458ff9b.png)

嗯，一样的问题，弄了好几遍都不行

**Comment by zhoujinshi** [comment]
字体图标库被修改了，图标必须和CSS样式的名称一致，可以去https://www.iconfont.cn/ 阿里巴巴字体图标库从新编辑下。

搞不定就只能还原字体库，等新的字体库兼容后再发布。

**Comment by mzl0408** [comment]
> 字体图标库被修改了，图标必须和CSS样式的名称一致，可以去https://www.iconfont.cn/ 阿里巴巴字体图标库从新编辑下。
> 
> 搞不定就只能还原字体库，等新的字体库兼容后再发布。

怎么还原呢，能给步骤吗

**Comment by davidtall** [comment]
> > 字体图标库被修改了，图标必须和CSS样式的名称一致，可以去https://www.iconfont.cn/ 阿里巴巴字体图标库从新编辑下。
> > 搞不定就只能还原字体库，等新的字体库兼容后再发布。
> 
> 怎么还原呢，能给步骤吗

还原到上一个版本去编译就可以了 git checkout 48bfe90f97f76135f79ead2fd878445b8f125387

https://github.com/kenzok78/luci-theme-argonne/commits/main

**Comment by kenzok8** [comment]
#4  已修复，让大伙折腾了

**Comment by mzl0408** [comment]
> #4 已修复，让大伙折腾了
刚重新试了下，还是不行，我删除重新编译下再看看，感谢大佬

**Comment by davidtall** [comment]
> 

清除浏览器缓存，CTRL +F5

**Comment by davidtall** [comment]
> #4 已修复，让大伙折腾了

最新的版本有个问题，点击左侧的二级菜单，菜单就会自动收回，旧的版本是展开不收回的。但我试了原版作者的最新版1.7.3，也是这样

**Comment by zhoujinshi** [comment]
最原始的luci-theme-argon作者是使用菜单是不会收回的，luci-theme-argonne新版本确实会，每次都要从新点开主菜单。

**Comment by mzl0408** [comment]
> 原作者是使用菜单是不会收回的，新版本确实会，每次都要从新点开主菜单。
原作者新版本也会收回了，更新的版本好多问题啊

**Comment by kenzok8** [comment]
上游已修复，同步更新了

**Comment by almazkairat** [comment]
嘿
openwrt 21.02 的问题仍然存在

**Comment by zhoujinshi** [comment]
> 嘿 openwrt 21.02 的问题仍然存在

请问你有拉取最新代码重新编译没有
