### ISSUE TITLE
1.7.3 登录页空白的问题

### ISSUE THREAD

**Issue by RicKy041229** [kenzok78/luci-theme-argone#6]
访问路由器管理地址时会跳转到 /cgi-bin/luci/，此时登录页面为空白，需要在后面加入 /admin 才会正常显示登录页，其它主题没有这个问题

**Comment by xiaopang0v0** [comment]
未能复现，请详细描述一下，最好打开开发者工具（ F12 ）的网络界面，那样方便排查是哪里出了问题

**Comment by selboo** [comment]
我也遇到了, 返回的 response 不完整

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/1220576/236616679-8cbe8d7e-6197-43cd-a941-8e432248fcd4.png">
